from .vision_widget import VisionWidget
from .gcode_widget import GcodeWidget
from .data_plot_widget import DataPlotWidget
from .platform_status_widget import PlatformStatusWidget
from .command_widget import CommandWidget
from .connection_widget import ConnectionWidget
from .log_widget import LogWidget
from .home_widget import HomeWidget
from .vision_page_widget import VisionPageWidget
from .ir_widget import IRPageWidget
from .job_sequence_widget import JobSequenceWidget
from .calibration_dialog import CalibrationDialog