import numpy as np
import pandas as pd

def extrusion_statistics(steps: list[pd.DataFrame], 
                         clip: int = 0):
    """
    Compute statistics for each extrusion step after clipping the initial data points.
    The statistics include mean feedrate, mean temperature, mean extrusion force, and standard deviation of extrusion force.

    Parameters
    ----------
    steps : list[pd.DataFrame]
        A list of DataFrames, each representing an extrusion step with columns "feedrate_mms", "temperature_C", and "extrusion_force_N".
    clip : int, optional
        The number of initial data points to clip from each step before computing statistics, by default 0.
    
    Returns
    -------
    pd.DataFrame
        A DataFrame containing the computed statistics for each step, with columns "feedrate_mms", "temperature_C", "extrusion_force_N_mean", and "extrusion_force_N_std".
    
    Example
    -------
    >>> stats = extrusion_statistics(cleaned_steps, clip=10)
    """
    stats = []
    for step in steps:
        clipped = step[clip:]
        stat = {
            "feedrate_mms": clipped["feedrate_mms"].mean(),
            "temperature_C": clipped["temperature_C"].mean(),
            "extrusion_force_N_mean": clipped["extrusion_force_N"].mean(),
            "extrusion_force_N_std": clipped["extrusion_force_N"].std()
        }
        stats.append(stat)
    return pd.DataFrame(stats)

def clean_data(raw_data: pd.DataFrame,
               feedrate_col: str = "feedrate_mms"):
    """
    Parameters
    ----------
    raw_data : pd.DataFrame
        the original table generated by HEPiC
    feedrate_col : str
        the name of the feedrate column in the data table. This is used to identify the parameter steps.

    Returns
    -------
    cleaned_steps : list
        a list of pd.DataFrame, each of which is regarded as a single parameter set. 
    data_clean : pd.DataFrame
        the cleaned data table.
    step_length : int
        the inferred step length, which is used as a reference for filtering out short steps.

    Examples
    --------
    >>> cleaned_steps, data_clean, step_length = clean_data(data)
    """

    # define tiny
    eps = np.finfo(float).eps

    # remove tiny force entries
    data_clean = raw_data.loc[(raw_data.extrusion_force_N >= eps)&(raw_data[feedrate_col]>eps)].copy()

    # time start at 0
    data_clean.loc[:, "time_s"] -= data_clean.time_s.min()
    # min_length = step_length // 2
    
    ####
    data_clean.loc[:, "gradient"] = data_clean[feedrate_col].diff().abs()
    data_clean.loc[:, "is_flat"] = data_clean["gradient"].lt(eps)
    data_clean.loc[:, "step_id"] = (~data_clean["is_flat"]).cumsum()

    # infer the step length
    step_length = 0
    for step, g_step in data_clean.groupby("step_id"):
        step_length = max(step_length, len(g_step))
    
    print(f"inferred step length: {step_length}")

    min_length = step_length // 2

    # filter out short steps
    cleaned_steps = []
    for step, g_step in data_clean.groupby("step_id"):
        if len(g_step) > min_length:
            cleaned_steps.append(g_step)
    
    print(f"number of steps: {len(cleaned_steps)}")

    return cleaned_steps, data_clean, step_length